### ISSUE TITLE
NameError: name 'run_broadband_metalens' is not defined

### ISSUE THREAD

**Issue by Lakemso** [DeanHazineh/DFlat_Public#23]
Hello,
I tried to run the script (Demo_optimize_broadband_rcwa_metalens) on the colab.research.google.com website. I faced the following error. could you please help me to solve it?
____________________________________________________________________________________
NameError                                 Traceback (most recent call last)
[<ipython-input-1-5bac449d5bf1>](https://localhost:8080/#) in <cell line: 1>()
----> 1 run_broadband_metalens(num_epochs=50, try_gpu=True)

NameError: name 'run_broadband_metalens' is not defined
_________________________________________________________________________________________

Regards

**Comment by DeanHazineh** [comment]
Resolved
